// Localization maps for English and Kannada
const Map<String, Map<String, String>> localizedStrings = {
  'English': {
    'appTitle': 'Community Empowerment',
    'schemesTitle': 'Schemes',
    'schemeType': 'Scheme Type',
    'sector': 'Sector',
    'year': 'Year',
    'explore': 'Explore',
    'back': 'Back',
    'detailsTitle': 'Scheme Details',
    'schemeName': 'Scheme Name',
    'sectorLabel': 'Sector',
    'startDate': 'Started Date',
    'benefits': 'Benefits',
    'eligibility': 'Eligibility',
    'moreDetails': 'More Details',
    'share': 'Share',
    'noSchemes': 'No schemes found.',
  },
  'Kannada': {
    'appTitle': 'ಸಮುದಾಯ ಸಬಲೀಕರಣ',
    'schemesTitle': 'ಯೋಜನೆಗಳು',
    'schemeType': 'ಯೋಜನೆಯ ಪ್ರಕಾರ',
    'sector': 'ಕ್ಷೇತ್ರ',
    'year': 'ವರ್ಷ',
    'explore': 'ಹೆಚ್ಚಿನ ಮಾಹಿತಿ',
    'back': 'ಹಿಂದೆ',
    'detailsTitle': 'ಯೋಜನೆಯ ವಿವರಗಳು',
    'schemeName': 'ಯೋಜನೆಯ ಹೆಸರು',
    'sectorLabel': 'ಕ್ಷೇತ್ರ',
    'startDate': 'ಪ್ರಾರಂಭದ ದಿನಾಂಕ',
    'benefits': 'ಪ್ರಯೋಜನಗಳು',
    'eligibility': 'ಅರ್ಹತೆ',
    'moreDetails': 'ಹೆಚ್ಚಿನ ವಿವರಗಳು',
    'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
    'noSchemes': 'ಯಾವುದೇ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
  },
};
